; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lilygo-t-dongle-s3]
extends = env_light
board = esp32-s3-devkitc-1
board_build.partitions = default_8MB.csv
build_src_filter = ${env.build_src_filter} +<../boards/lilygo-t-dongle-s3>
build_flags =
	${env_light.build_flags}
	-Iboards/lilygo-t-dongle-s3
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	; Screen setup
	-D TFT_WIDTH=80
	-D TFT_HEIGHT=160
	-D TFT_MOSI=3
	-D TFT_SCLK=5
	-D TFT_CS=4
	-D TFT_DC=2
	-D TFT_RST=1
	-D TFT_BL=38
	; Single button
	-D BUTTON_PIN=0
	-D HAS_1_BUTTON
	; SD card
	-D SD_MMC_CLK=12
	-D SD_MMC_CMD=11
	-D SD_MMC_D0=13
	-D DEVICE_NAME='"Lilygo T-Dongle S3"'
